apiVersion: v1
kind: Service
metadata:
  name: mpi-master
  labels:
    service: mpi-master
spec:
  type: NodePort
  ports:
  - port: 22
    nodePort: 30001
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: mpi-master-deployment
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: mpi-master-deployment
    spec:
      volumes:
        - name: ssh-keys
          secret:
            secretName: ssh-key-secret
            items:
              - key: id_rsa
                path: id_rsa
                mode: 0600
              - key: id_rsa.pub
                path: id_rsa.pub
                mode: 0600
              - key: authorized_keys
                path: authorized_keys
                mode: 0644
      containers:
      - name: kube-mpi
        # Run this image
        image: javawolfpack/base-centos-mpi
        imagePullPolicy: Always
        ports:
          - containerPort: 22
        volumeMounts:
          - name: ssh-keys
            readOnly: false
mountPath: /home/mpi/.ssh/
